### ISSUE TITLE
Database credentials docker-compose

### ISSUE THREAD

**Issue by leslietech** [PaulLebmann/docker-gibbonedu#2]
Thanks for building this repo. I have successfully installed Gibbon, and deployed it with the Traefik reverse proxy (I had to tweak the compose file and add config and environment variables for Traefik). 

Gibbon is running, however, I still had to manually enter the database credentials in the Gibbon setup wizard. Is that how you had it planned, or the database details are meant to auto-populate. If that is how it is planned then it is fine (because the database got properly created).

**Comment by PaulLebmann** [comment]
Hi @leslietech !
Thanks for your feedback!
When I started I tried prepopulating the gibbon config.php via the environment variables. It did not work out. So it is still necessary to run through the whole web based setup process and also enter the database credentials there. I am going to make this more clear in the readme.md and will change the docker-compose files so that the database related variables are not passed to the php container.

**Comment by leslietech** [comment]
You're welcome. You did something amazing here. At least I now know that the database variables do not get passed to the php container.

**Comment by PaulLebmann** [comment]
I finally removed the environment variables from the php container since they could not be used there anyway and I hope I could improve the description of the setup process in the readme.

**Comment by leslietech** [comment]
Thanks @PaulLebmann. Looks good.

**Comment by leslietech** [comment]
I have just successfully performed a fresh install with 23.0.02 set in the .env file and it looks good. I got the following:

![Version23 0 02](https://user-images.githubusercontent.com/49253776/173217073-f55ec1fe-18c8-4259-b63d-a3a6ba0b9bfa.PNG)

**Comment by leslietech** [comment]
Sorry, version 23.0.02 just displayed the following loading animation, no matter where I try to navigate to on the app.

![Loading](https://user-images.githubusercontent.com/49253776/173217433-9774fb3a-4312-4b92-af14-fd033f192e14.PNG)

This started after I tried to activate the alarm in the app. So I downgraded to v23.0.00 and then activated the alarm and it did the same :(. Can you recreate this in your install? Looks like I may have to hide the alarm for now or avoid clicking on it.

**Comment by PaulLebmann** [comment]
I did a fresh Installation with the demodata just after cloning the repo and moving my other .env.

After activating the Alarm (admin > system admin > Sound Alarm; choose one and submit) on 23.0.02 I get the Alarm message on every site load including the dashboard and after disabling the alarm gibbon works for me as expected. (on Firefox on Lubuntu 18.04)

This could be be JavaScript related since I get the loading bar when visiting the system admin site (your first screenshot) on my test gibbon site via a VPN. So my browser, and therefore the script, is not able to connect to the gibbonedu.org to check if it is the latest version.

Do you see the alarm window before this behavior or not?
If not, probably the JavaScript is hanging. Are you using any JS - blocker in your browser?

**Comment by leslietech** [comment]
> Do you see the alarm window before this behavior or not?

Yes, I see the alarm window the first time. I then select the alarm, and after I activate it, I get that loading window instead. Afterwards, that window comes up whenever I try to click on any link. Not sure if it is caused by me running the site through Traefik. Am running it on a Linode. I'll try building a new site, shut down everything else that is running in Docker, and see if the alarm works. In the meantime, I have disabled the alarm feature.

**Comment by leslietech** [comment]
> I'll try building a new site, shut down everything else that is running in Docker, and see if the alarm works.

I am hoping that this is a memory issue at my end.

**Comment by PaulLebmann** [comment]
> I see the alarm window the first time. I then select the alarm, and after I activate it, I get that loading window instead.

So just to be clear:
You are using the feature described at [https://docs.gibbonedu.org/administrators/misc/sounding-an-alarm/]( https://docs.gibbonedu.org/administrators/misc/sounding-an-alarm/ ) and not a separate module?
Do you see the big red square after loading any site in your gibbon installation or do you just see the config page for the alarm?

**Comment by leslietech** [comment]
> You are using the feature described at https://docs.gibbonedu.org/administrators/misc/sounding-an-alarm/ and not a separate module?
> Do you see the big red square after loading any site in your gibbon installation or do you just see the config page for the alarm?

Yes, I am using this feature. I do not even get to the red alert background. Here are my steps:

I click on "Sound Alarm"

![A1](https://user-images.githubusercontent.com/49253776/174230023-5fa0cf6f-3210-40b2-b6bc-52085d6ece2c.PNG)

I choose the alarm type from the drop down

![A2](https://user-images.githubusercontent.com/49253776/174230031-df6a69fa-4e5c-43db-af1f-09ed7bd1d11a.PNG)

I click on "Submit"

![A3](https://user-images.githubusercontent.com/49253776/174230040-3f219372-b71a-4cd4-bffc-9ef8976b7b58.PNG)

I then see the loading screen. However, whenever I click on the screen, the loading animation goes away. When I click on any link or button afterwards, the animation comes up. I have tried purging cache, restarting the stack, restarting the server, to no avail.

![A4](https://user-images.githubusercontent.com/49253776/174230048-e9aa251b-1cee-4e2d-9586-a32643314fd0.PNG)

At some point, I start getting these messages that variables are not set, even though they are. This error about the network that is defined and not used it due to the fact that in my compose file, I set it up so that it defines the app's network using `${GIBBON_SITENAME}_network`, so at some point, it stops seeing the variable `${GIBBON_SITENAME}`. I wonder what causes the install to, at times, not see the env variables.

![A6-error](https://user-images.githubusercontent.com/49253776/174230056-43ed34b6-341d-4f32-93eb-bd3157c2758b.PNG)

I'm glad that the alarm feature works at your end. I will continue troubleshooting my install to see what I missed. Since I am running my test on a VPS running Traefik, I will create a separate install in my local Docker, using your original repo, so I can compare the installs and see where I messed up. Please consider this issue resolved as you can use the alarm in your local install.

**Comment by leslietech** [comment]
I have just discovered that the loading animation goes away when I go back to the Alarm page and set it to "None" and then submit. I'll continue troubleshooting this. Thanks.

**Comment by PaulLebmann** [comment]
> I then see the loading screen. However, whenever I click on the screen, the loading animation goes away.

So it closes the overlay, this is the same behavior as when it is showing the additional div.
Did you try to disable your browser addons or try it in a private browser window?

> At some point, I start getting these messages that variables are not set, even though they are. This error about the network that is defined and not used it due to the fact that in my compose file, I set it up so that it defines the app's network using `${GIBBON_SITENAME}_network`, so at some point, it stops seeing the variable `${GIBBON_SITENAME}`. I wonder what causes the install to, at times, not see the env variables.

Does this only happen when you start the stack with docker-compose up? It looks like output from docker-compose and not like logs from your containers.
Are those the only missing variables docker-compose is complaining about or are all variables form your .env missing?
I only get similar errors if I try to run docker-compose up or docker-compose restart in a directory other than the project root, where the .env file is located. Could this be the problem?

> I have just discovered that the loading animation goes away when I go back to the Alarm page and set it to "None" and then submit.

If you disable the alarm it does not try to build the overlay and so there is no problem. Before focusing too much on the server side, have a look at the JavaScript side. To me it seems like the problem could be there. Try another browser (freshly installed, without addons).

**Comment by leslietech** [comment]
> Did you try to disable your browser addons or try it in a private browser window?

Yes, it does the same in a private browser window.

> Does this only happen when you start the stack with docker-compose up? It looks like output from docker-compose and not like logs from your containers.

Yes, it is definitely not from the containers.

> Are those the only missing variables docker-compose is complaining about or are all variables form your .env missing?

The DB variables are also in the .env, but the DB variables are not included in the error. Strange.

> I only get similar errors if I try to run docker-compose up or docker-compose restart in a directory other than the project root, where the .env file is located. Could this be the problem?

Yes, with `docker-compose up -d`. I will check this again the next time it happened. it could be that I was in the wrong folder. I have about 5 Gibbon sites running...lol. This particular issue could just be a PEBKAC :).
